# Generated by Django 4.2.4 on 2023-08-30 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_rename_category_teams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
