# Generated by Django 4.2.4 on 2023-08-30 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_rename_crated_at_posts_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='texts',
            new_name='body',
        ),
    ]
